{% set version = "1.1.3" %}

package:
  name: httpretty
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/httpretty/httpretty-{{ version }}.tar.gz
  sha256: 229ade39175ea4324e767f29dc24e5f846fbc72bf80e1a919b2547a6574ff601

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - six

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - httpretty

about:
  home: http://github.com/gabrielfalcao/httpretty
  license: MIT
  license_file: COPYING
  summary: HTTP client mock for Python

extra:
  recipe-maintainers:
    - ocefpaf
